# Generated by Django 5.2.8 on 2025-11-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de Identificación')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión Libre')], max_length=15, verbose_name='Estado Civil')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pais_nacimiento', models.CharField(default='Colombia', max_length=100, verbose_name='País de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('direccion_residencia', models.CharField(max_length=255, verbose_name='Dirección de Residencia')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('grupo_etnico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo Étnico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de la Visita')),
                ('sintomas_actuales', models.TextField(verbose_name='Síntomas/Descripciones del Momento')),
                ('diagnostico_principal', models.TextField(verbose_name='Diagnóstico del Paciente (en esta visita)')),
                ('otras_comorbilidades', models.TextField(blank=True, null=True, verbose_name='Otras Comorbilidades y Antecedentes')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='myapp.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica (Visita)',
                'verbose_name_plural': 'Historias Clínicas (Visitas)',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
