# Generated by Django 5.2.8 on 2025-11-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paciente_historiaclinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['-fecha_visita'], 'verbose_name': 'Historia Clínica', 'verbose_name_plural': 'Historias Clínicas '},
        ),
    ]
