# Generated by Django 5.2.8 on 2025-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_historiaclinica_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnostico_final',
            field=models.CharField(blank=True, choices=[('CRC', 'Cáncer Colorrectal'), ('CO', 'Paciente Control (Sano / Otras Condiciones)')], max_length=3, null=True, verbose_name='Diagnóstico Final'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='predicciones',
            field=models.JSONField(blank=True, null=True, verbose_name='Predicciones NLP'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tratamientos_actuales',
            field=models.TextField(default='', verbose_name='Tratamientos/Examenes realizados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico_principal',
            field=models.TextField(verbose_name='Diagnóstico del Profecional'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sintomas_actuales',
            field=models.TextField(verbose_name='Síntomas del Paciente'),
        ),
    ]
