# Generated by Django 5.2.8 on 2025-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_historiaclinica_diagnostico_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='diagnostico_final',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='predicciones',
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico_principal',
            field=models.TextField(verbose_name='Diagnóstico del Profesional'),
        ),
    ]
