# Generated by Django 5.2.8 on 2025-11-26 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_historiaclinica_diagnostico_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicciones_nlp', models.JSONField(verbose_name='Predicciones NLP (JSON)')),
                ('diagnostico_final', models.CharField(choices=[('CCR', 'Cáncer Colorrectal'), ('CO', 'Paciente Control')], max_length=3, verbose_name='Diagnóstico Final')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Análisis')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_finales', to='myapp.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Análisis Final',
                'verbose_name_plural': 'Análisis Finales',
                'ordering': ['-fecha_analisis'],
            },
        ),
    ]
