# Generated by Django 5.2.8 on 2025-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_analisisfinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Recurso')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor / Institución')),
                ('descripcion', models.TextField(verbose_name='Breve Descripción')),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro / Guía'), ('ARTICULO', 'Artículo Científico'), ('VIDEO', 'Video / Conferencia')], default='ARTICULO', max_length=20)),
                ('url_recurso', models.URLField(verbose_name='Enlace al recurso')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen de Portada (Opcional)')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
            ],
        ),
    ]
