# Generated by Django 5.2.8 on 2025-12-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_recursomedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titular de la Noticia')),
                ('resumen', models.TextField(verbose_name='Resumen Breve')),
                ('url_noticia', models.URLField(verbose_name='Enlace a la Noticia Completa')),
                ('url_imagen', models.URLField(verbose_name='URL de la Imagen de Portada')),
                ('fuente', models.CharField(max_length=100, verbose_name='Nombre de la Fuente (Ej. El Tiempo)')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
